FROM continuumio/anaconda3

RUN pip install shapely -i https://pypi.douban.com/simple
RUN pip install torch -i https://pypi.douban.com/simple
RUN pip install torchvision -i https://pypi.douban.com/simple